### ISSUE TITLE
博客留言板

### ISSUE THREAD

**Issue by kooritea** [kooritea/kooritea.github.io#2]

**Comment by kooritea** [comment]
试试看

**Comment by kooritea** [comment]
留言板又可以用了

**Comment by shoushangdetuolaji** [comment]
沙发

**Comment by voidoath** [comment]
新年快乐！

**Comment by AXFOX** [comment]
好久不留言了，新年快乐呀。

**Comment by kooritea** [comment]
@AXFOX 新年快乐！

**Comment by AXFOX** [comment]
上学之后好久不逛博客了，就简单维持着自己的博客更新。明天清明应该放一天假，所以来逛逛。

**Comment by Riceneeder** [comment]
大佬，我给Electronic-WeChat打了UOS补丁，能用了，你能开仓库继续维护吗？  [仓库](https://github.com/Riceneeder/electronic-wechat)
![20220918_15h51m20s_grim](https://user-images.githubusercontent.com/86492950/190891756-279f7138-8358-486b-af72-bdafac3cc101.png)

**Comment by kooritea** [comment]
@Riceneeder 竟然还有人用这个。，我在首页贴上你仓库的连接，你在自己的仓库维护吧

**Comment by Riceneeder** [comment]
> @Riceneeder 竟然还有人用这个。，我在首页贴上你仓库的连接，你在自己的仓库维护吧

好的
